"""CRUD operations for Area model."""

from sqlalchemy import func, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.area import Area
from app.models.competent_authority import CompetentAuthority


async def create(
    session: AsyncSession,
    area_id: str | None,
    area_name: str | None,
    competent_authority_id: int,
    filename: str,
    filedata: bytes,
) -> Area:
    """
    Create a new area.

    Args:
        session: Async database session
        area_id: Optional functional ID. If not provided, auto-generated by model.
        area_name: Optional human-readable name (max 128 characters).
        competent_authority_id: Foreign key to CompetentAuthority (integer)
        filename: Filename (64 characters max)
        filedata: File data (binary)

    Returns:
        Created Area instance

    Note:
        The combination of (area_id, competent_authority_id, created_at) is unique to enable versioning.
    """
    area = Area(
        area_id=area_id,
        area_name=area_name,
        competent_authority_id=competent_authority_id,
        filename=filename,
        filedata=filedata,
    )
    session.add(area)
    await session.flush()
    await session.refresh(area)
    return area


async def delete(session: AsyncSession, area_id: int) -> bool:
    """
    Delete an area by technical id.

    Args:
        session: Async database session
        area_id: Area technical id (integer)

    Returns:
        True if deleted, False if not found
    """
    area = await get_by_id(session, area_id)
    if area is None:
        return False

    await session.delete(area)
    await session.flush()
    return True


async def exists(session: AsyncSession, area_id: int) -> bool:
    """
    Check if an area exists by technical id.

    Args:
        session: Async database session
        area_id: Area technical id (integer)

    Returns:
        True if exists, False otherwise
    """
    stmt = select(Area.id).where(Area.id == area_id)
    result = await session.execute(stmt)
    return result.scalar_one_or_none() is not None


async def count(session: AsyncSession) -> int:
    """
    Count all current areas (ended_at IS NULL).

    Args:
        session: Async database session

    Returns:
        Total number of current areas
    """
    stmt = select(func.count()).select_from(Area).where(Area.ended_at.is_(None))
    result = await session.execute(stmt)
    return result.scalar_one()


async def get_all(
    session: AsyncSession, offset: int = 0, limit: int | None = None
) -> list[Area]:
    """
    Get current areas with pagination (ended_at IS NULL).

    Args:
        session: Async database session
        offset: Number of records to skip (default: 0)
        limit: Maximum number of records to return (default: no limit)

    Returns:
        List of current Area instances
    """
    stmt = (
        select(Area)
        .where(Area.ended_at.is_(None))
        .order_by(Area.created_at.desc())
        .offset(offset)
    )
    if limit is not None:
        stmt = stmt.limit(limit)

    result = await session.execute(stmt)
    return list(result.scalars().all())


async def get_by_id(session: AsyncSession, area_id: int) -> Area | None:
    """
    Get an area by technical id (internal use only).

    Args:
        session: Async database session
        area_id: Area technical id (integer)

    Returns:
        Area instance or None if not found
    """
    stmt = select(Area).where(Area.id == area_id)
    result = await session.execute(stmt)
    return result.scalar_one_or_none()


async def get_by_area_id(session: AsyncSession, area_id: str) -> Area | None:
    """
    Get current area by functional ID (ended_at IS NULL).

    Args:
        session: Async database session
        area_id: Area functional ID (UUID string)

    Returns:
        Current Area instance for the given area_id, or None if not found
    """
    stmt = select(Area).where(
        Area.area_id == area_id,
        Area.ended_at.is_(None),
    )
    result = await session.execute(stmt)
    return result.scalar_one_or_none()


async def get_by_competent_authority_id(
    session: AsyncSession,
    competent_authority_id: int,
    offset: int = 0,
    limit: int | None = None,
) -> list[Area]:
    """
    Get areas by competent authority id (foreign key) with pagination.

    Args:
        session: Async database session
        competent_authority_id: Competent authority id (foreign key)
        offset: Number of records to skip (default: 0)
        limit: Maximum number of records to return (default: no limit)

    Returns:
        List of Area instances for the given competent authority
    """
    stmt = (
        select(Area)
        .where(Area.competent_authority_id == competent_authority_id)
        .offset(offset)
    )
    if limit is not None:
        stmt = stmt.limit(limit)

    result = await session.execute(stmt)
    return list(result.scalars().all())


async def get_by_competent_authority_id_str(
    session: AsyncSession,
    competent_authority_id_str: str,
    offset: int = 0,
    limit: int | None = None,
) -> list[Area]:
    """
    Get current areas by competent authority functional ID (ended_at IS NULL).

    Args:
        session: Async database session
        competent_authority_id_str: Competent authority functional ID string (e.g., "0363")
        offset: Number of records to skip (default: 0)
        limit: Maximum number of records to return (default: no limit)

    Returns:
        List of current Area instances for the given competent authority
    """
    stmt = (
        select(Area)
        .join(CompetentAuthority, Area.competent_authority_id == CompetentAuthority.id)
        .where(
            CompetentAuthority.competent_authority_id == competent_authority_id_str,
            Area.ended_at.is_(None),
        )
        .order_by(Area.created_at.desc())
        .offset(offset)
    )
    if limit is not None:
        stmt = stmt.limit(limit)

    result = await session.execute(stmt)
    return list(result.scalars().all())


async def get_by_filename(
    session: AsyncSession, filename: str, offset: int = 0, limit: int | None = None
) -> list[Area]:
    """
    Get areas by filename with pagination.

    Args:
        session: Async database session
        filename: Area filename
        offset: Number of records to skip (default: 0)
        limit: Maximum number of records to return (default: no limit)

    Returns:
        List of Area instances matching the filename
    """
    stmt = select(Area).where(Area.filename == filename).offset(offset)
    if limit is not None:
        stmt = stmt.limit(limit)

    result = await session.execute(stmt)
    return list(result.scalars().all())


async def count_by_competent_authority_id_str(
    session: AsyncSession,
    competent_authority_id_str: str,
) -> int:
    """
    Count current areas by competent authority functional ID (ended_at IS NULL).

    Args:
        session: Async database session
        competent_authority_id_str: Competent authority functional ID string (e.g., "0363")

    Returns:
        Total number of current areas for the given competent authority
    """
    stmt = (
        select(func.count())
        .select_from(Area)
        .join(CompetentAuthority, Area.competent_authority_id == CompetentAuthority.id)
        .where(
            CompetentAuthority.competent_authority_id == competent_authority_id_str,
            Area.ended_at.is_(None),
        )
    )
    result = await session.execute(stmt)
    return result.scalar_one()


async def exists_any_by_area_id(
    session: AsyncSession,
    area_id: str,
) -> bool:
    """
    Check if any version of an area exists by functional ID (regardless of ended_at).

    Args:
        session: Async database session
        area_id: Area functional ID

    Returns:
        True if any version exists, False otherwise
    """
    stmt = select(func.count()).select_from(Area).where(Area.area_id == area_id)
    result = await session.execute(stmt)
    return result.scalar_one() > 0


async def get_by_area_id_and_competent_authority_id_str(
    session: AsyncSession,
    area_id: str,
    competent_authority_id_str: str,
) -> Area | None:
    """
    Get current area by functional ID and competent authority functional ID.

    Args:
        session: Async database session
        area_id: Area functional ID
        competent_authority_id_str: Competent authority functional ID string (e.g., "0363")

    Returns:
        Current Area instance or None if not found
    """
    stmt = (
        select(Area)
        .join(CompetentAuthority, Area.competent_authority_id == CompetentAuthority.id)
        .where(
            Area.area_id == area_id,
            CompetentAuthority.competent_authority_id == competent_authority_id_str,
            Area.ended_at.is_(None),
        )
    )
    result = await session.execute(stmt)
    return result.scalar_one_or_none()


async def get_area_id_map(
    session: AsyncSession,
    area_ids: list[str],
) -> dict[str, int]:
    """
    Fetch current areas by functional IDs in a single query (Validation flow Step 2).

    Returns a mapping of {functional_area_id: technical_id} for all current areas
    matching the given IDs. Used for O(1) referential integrity checks in bulk operations.

    Args:
        session: Async database session
        area_ids: List of area functional IDs to look up

    Returns:
        Dictionary mapping functional area_id to technical id
    """
    if not area_ids:
        return {}

    stmt = select(Area.area_id, Area.id).where(
        Area.area_id.in_(area_ids),
        Area.ended_at.is_(None),
    )
    result = await session.execute(stmt)
    return {row[0]: row[1] for row in result.all()}


async def mark_as_ended(
    session: AsyncSession,
    area_id: str,
    competent_authority_id: int,
) -> None:
    """
    Mark the current version of an area as ended (set ended_at = now()).

    Args:
        session: Async database session
        area_id: Area functional ID
        competent_authority_id: Competent authority technical ID (foreign key)
    """
    stmt = (
        update(Area)
        .where(
            Area.area_id == area_id,
            Area.competent_authority_id == competent_authority_id,
            Area.ended_at.is_(None),
        )
        .values(ended_at=func.now())
    )
    await session.execute(stmt)
    await session.flush()
